_id: 8cc6bcb0-9c0e-11e8-995f-5178b29ab3fb
metadata:
  author:
    first: Floyd
    last: Hilty
    email: fhilty@ufl.edu
    github_id: FHilty
  timestamp: '9 August, 2018'
  summary: Results for benchmark 1a
  implementation:
    name: MOOSE framework
    repo:
      url: 'https://github.com/FHilty/Benchmarks/blob/master/1a.i'
      version: a001b86
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '8'
    nodes: '1'
benchmark:
  id: 1a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '1244'
        sim_time: '1000000'
  - name: memory_usage
    values:
      - unit: KB
        value: '1016432'
  - name: MOOSE_FH_1a
    url: >-
      https://gist.githubusercontent.com/FHilty/af553a152a933bba5552a4eaa7313069/raw/0dba93516118065419bda950993381f04af1a879/MOOSE_FH_1a.csv
    format:
      type: csv
      parse:
        time: number
        total_energy: number
    description: Simulation data for benchmark 1a
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_energy
        as: 'y'
date: 1533844694
