_id: fc221f50-9c0e-11e8-995f-5178b29ab3fb
metadata:
  author:
    first: Floyd
    last: Hilty
    email: fhilty@ufl.edu
    github_id: FHilty
  timestamp: '9 August, 2018'
  summary: Results for benchmark 1b
  implementation:
    name: MOOSE
    repo:
      url: 'https://github.com/FHilty/Benchmarks/blob/master/1b.i'
      version: a001b86
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '8'
    nodes: '1'
benchmark:
  id: 1b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '1206'
        sim_time: '1000000'
  - name: memory_usage
    values:
      - unit: KB
        value: '915056'
  - name: MOOSE_FH_1b
    url: >-
      https://gist.githubusercontent.com/FHilty/999a83b9bae0f96b446b00512b9ae5b2/raw/83228b9d49f73b7d4136d440a3c5a4d54de60d5f/MOOSE_FH_1b.csv
    format:
      type: csv
      parse:
        time: number
        total_energy: number
    description: Data for benchmark 1b
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_energy
        as: 'y'
date: 1533844881
