_id: 8fd34670-a47f-11e8-9ae0-593cf187bda1
metadata:
  author:
    first: Ian
    last: Greenquist
    email: ikg5018@psu.edu
    github_id: itgreenquist
  timestamp: '29 March, 2018'
  summary: Benchmark Problem 1a
  implementation:
    name: MOOSE framework
    repo:
      url: 'https://github.com/itgreenquist/moose/tree/benchmark'
      version: fa4420c
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '8'
    nodes: '1'
benchmark:
  id: 1a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '1774'
        sim_time: '1073370'
  - name: memory_usage
    values:
      - unit: KB
        value: '37755265'
  - name: free_energy
    url: >-
      https://github.com/itgreenquist/moose/blob/benchmark/benchmark_uploads/prob_1/a_energy.csv
    format:
      type: csv
      parse:
        time: number
        total_energy: number
    description: Free energy for Benchmark Problem 1a
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_energy
        as: 'y'
date: 1534772841
