benchmark: 
    id: 7a
    version: 0
metadata: 
    summary: Benchmark of the SymPhas API. The implementation written for this
        problem uses the forward Euler (central-space forward-time) finite 
        difference scheme, which applies a 5-point Laplacian stencil.
    author: 
        first: Steven
        last: Silber
        email: ssilber@uwo.ca
        github_id: MetricManifold
    timestamp: ''
    hardware: 
        acc_architecture: 'none'
        clock_rate: 3.2
        cores: 12
        cpu_architecture: x86_64
        nodes: 1
        parallel_model: threaded
    implementation: 
        container_url: '29 October, 2021'
        name: SymPhas
        repo:
            url: https://github.com/SoftSimu/SymPhas
            version: e12d3c54d2c24ad68de5034fff8d947e1766cf6e
data: 
-   name: run_time
    values: 
    -   sim_time: 0.0
        wall_time: 0.0
-   name: memory_usage
    values: 
    -   unit: KB
        value: 0
-   name: temporal
    format: 
        type: csv
        parse:
            time_step: number
            L2_error: number
    url: symphas_pfhub_L2_dt.csv
    description: Convergence data for varying time step size. The spatial
        step is fixed to a value of 0.002. 
-   name: spatial
    format:
        type: csv
        parse:
            mesh_size: number
            L2_error: number
    url: symphas_pfhub_L2_h.csv
    description: Convergence data for varying spatial step size. The time
        step is fixed to a value of 0.001. 
