_id: 5192bb60-a480-11e8-9ae0-593cf187bda1
metadata:
  author:
    first: Ian
    last: Greenquist
    email: ikg5018@psu.edu
    github_id: itgreenquist
  timestamp: '19 March, 2018'
  summary: Benchmark Problem 1b
  implementation:
    name: MOOSE framework
    repo:
      url: 'https://github.com/itgreenquist/moose/tree/benchmark'
      version: fa4420c
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '8'
    nodes: '1'
benchmark:
  id: 1b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '2280'
        sim_time: '983023'
  - name: memory_usage
    values:
      - unit: KB
        value: '377502512'
date: 1534773167
