_id: a7858cb0-9c0f-11e8-995f-5178b29ab3fb
metadata:
  author:
    first: Floyd
    last: Hilty
    email: fhilty@ufl.edu
    github_id: FHilty
  timestamp: '9 August, 2018'
  summary: Results for benchmark 1d
  implementation:
    name: MOOSE framework
    repo:
      url: 'https://github.com/FHilty/Benchmarks/blob/master/1d.i'
      version: a001b86
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '8'
    nodes: '1'
benchmark:
  id: 1d
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '5560'
        sim_time: '1000000'
  - name: memory_usage
    values:
      - unit: KB
        value: '2025888'
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/FHilty/ed6debf7e2c3c5aae26d5372de29f1cf/raw/9704c6761d88b91d5e0fcb3e2e611b7e147aa628/MOOSE_FH_1d.csv
    format:
      type: csv
      parse:
        time: number
        total_energy: number
    description: Data for benchmark 1d
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_energy
        as: 'y'
date: 1533845168
